"""Backward-compatible imports for the canonical :mod:`vla_sim.contracts` module."""

from vla_sim.contracts import (
    ACTION_DIM,
    ACTION_KEY,
    DEFAULT_ACTION_SPEC,
    IMAGE_KEY,
    WRIST_IMAGE_KEY,
    STATE_DIM,
    STACK_STATE_DIM,
    STATE_KEY,
    TASK_KEY,
    ActionSpec,
    ContractError,
    ObservationAdapter,
    StackObservationAdapter,
    PickPlaceObservationAdapter,
    validate_observation,
    validate_stack_observation,
    validate_pick_place_observation,
)

__all__ = [
    "ACTION_DIM",
    "ACTION_KEY",
    "DEFAULT_ACTION_SPEC",
    "IMAGE_KEY",
    "WRIST_IMAGE_KEY",
    "STATE_DIM",
    "STACK_STATE_DIM",
    "STATE_KEY",
    "TASK_KEY",
    "ActionSpec",
    "ContractError",
    "ObservationAdapter",
    "StackObservationAdapter",
    "PickPlaceObservationAdapter",
    "validate_observation",
    "validate_stack_observation",
    "validate_pick_place_observation",
]
